# This is a basic workflow to help you get started with Actions

name: Automated Code Review

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automtedCodeReview:
    name: Automated Code Review
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/securityReview.yml
